//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BirthCertificate
    {
        public int BirthCertificateId { get; set; }
        public string Series { get; set; }
        public int Number { get; set; }
        public string Description { get; set; }
    
        public virtual Child Child { get; set; }
    }
}
