//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public int ChildId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        //public int SexOfChild { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int AddressId { get; set; }
        public Nullable<int> Kindergarten_KindergartenId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual BirthCertificate BirthCertificate { get; set; }
        public virtual Kindergarten Kindergarten { get; set; }
        public virtual Order Order { get; set; }
    }
}
