//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public int ChildId { get; set; }
        public System.DateTime RegistrationTime { get; set; }
        public int KindergartenId { get; set; }
    
        public virtual Child Child { get; set; }
        public virtual User User { get; set; }
    }
}
