//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int StaffId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> StaffPositionId { get; set; }
        public Nullable<int> KindergartenId { get; set; }
    
        public virtual Kindergarten Kindergarten { get; set; }
        public virtual StaffPosition StaffPosition { get; set; }
    }
}
