// <auto-generated />
namespace RegistrationSystem.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class reg_time : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reg_time));
        
        string IMigrationMetadata.Id
        {
            get { return "201705180822077_reg_time"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
